### ISSUE TITLE
Grid Count Pop-Up Q

### ISSUE THREAD

**Issue by alemulli** [joshwalthall/sketchy-grid#2]
```
function changeGridCount() {
    const promptMessage = "Please enter a new grid count as a whole number between 1 and 100"
    let newGridCount = parseInt(prompt(promptMessage, `${gridCount}`));
    
    if (Number.isNaN(newGridCount)) {
        alert("Invalid entry. Please try again.");
    } else if (newGridCount < 1 || newGridCount > 100) {
        alert("Grid count not within valid range. Please try again.");
    } else {
        gridCount = newGridCount;
        clearGrid();
    };
};
```

Would you like this to be a nicely styled modal pop-up instead? If so I can get that going for you :)

**Comment by alemulli** [comment]
Just realized I was on the wrong repo - ahaha ignore if you want!

**Comment by joshwalthall** [comment]
No worries! I used the method of generating the grid on this one as a starting point for the grid generation in my [game of life](https://github.com/joshwalthall/game-of-life) project, but otherwise this one is pretty much done. Modals are a great idea, though! I got some practice with modal dialogs on my [library](https://github.com/joshwalthall/library) project and I definitely prefer them over alerts.
